  name: Auto-deploy
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  12.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Clean install dependencies
          run: npm ci

        - name: Run deploy script
          run: |
            git config user.name "covidnineteen"
            git checkout --orphan gh-pages
            npm run build
            git --work-tree dist add --all
            git --work-tree dist commit -m gh-pages
            git push origin HEAD:gh-pages --force
            rm  -r dist
            git checkout -f master
            git branch -D gh-pages
            npm install capture-website
            cp ./scripts/snapshot.js ./
            rm snapshot.png
            node snapshot.js
            git add snapshot.png
            git commit -m "New snapshot"
            git push
            
