name: Moonshot
on:
  push:
    branches:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
  
    - name: Generate Snapshot
      run: |
        npm ci
        rm snapshot.png
        node snapshot.js
        git checkout master
        git add snapshot.png
        git commit -m 'New snapshot file'
        git push
      
    - uses: actions/upload-artifact@v2
      with:
        name: tech-tracker-png
        path: 4th-gen/tech-tracker/local-file.png
